import { Remote, getRemote, setRemote } from '../multiturn/remote';
import { Move } from './types';

// To be autogenerated by preprocessor
export default class RemotePlayer {
  public static setup() {
    const moveRemote = (pred: (m: Move) => boolean) => {
      // TODO
      throw new Error('No validator');
    };
    setRemote<Move>(Move, moveRemote);
  }

  public getMove: Remote<Move>;

  public constructor() {
    this.getMove = getRemote(Move);
  }

}
